name: Windows-CRD1px

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Enter CRD code'
        required: true
      pincode:
        description: 'Six-digit Pin'
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Initializing Setup
        run: |
          powershell -ExecutionPolicy Bypass -File ./setup.ps1

      - name: Starting Chrome Remote Desktop
        run: |
          echo "Starting Chrome Remote Desktop..."
          powershell -Command "
            $authcode = '${{ github.event.inputs.authcode }}';
            $pincode = '${{ github.event.inputs.pincode }}';
            Write-Host 'Authcode: $authcode';
            Write-Host 'Pincode: $pincode';
            & 'C:\Program Files (x86)\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe' --code $authcode --pin $pincode
          "

      - name: Keep Alive
        run: |
          echo "Running Keep-Alive Script..."
          powershell -ExecutionPolicy Bypass -File ./timeout.ps1

