
name: Windows-CRD1px

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Enter CRD code'
        required: true
      pincode:
        description: 'Six-digit Pin'
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Initializing Setup
        run: |
          powershell -ExecutionPolicy Bypass -File ./setup.ps1

      - name: Starting CRD
        run: |
          echo "Starting CRD..."
          powershell -Command "$authcode='${{ github.event.inputs.authcode }}'; $pincode='${{ github.event.inputs.pincode }}'; ./start-crd.ps1 -AuthCode $authcode -Pin $pincode"

      - name: Keep Alive
        run: |
          echo "Running Keep-Alive Script..."
          powershell -ExecutionPolicy Bypass -File ./timeout.ps1
