name: Windows-CRD1px

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Enter CRD code'
        required: true
      pincode:
        description: 'Six digit Pin'
        required: true
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    # Checkout do repositório
    - name: Checkout repository
      uses: actions/checkout@v2  # Usando o checkout oficial

    # Depuração: Listar o conteúdo do diretório
    - name: List repository files
      run: dir
      shell: cmd

    # Garantir que o script setup.ps1 é executável
    - name: Make setup.ps1 executable
      run: |
        if (!(Test-Path "./setup.ps1")) { 
          Write-Error "setup.ps1 not found in current directory" 
        }
        Write-Host "setup.ps1 found, proceeding with execution"
      shell: pwsh

    # Executar o script setup.ps1
    - name: Initializing Setup
      shell: pwsh
      run: ./setup.ps1

    # Executar comando com inputs do workflow
    - name: Starting CRD
      shell: pwsh
      run: |
        $authcode = '${{ github.event.inputs.authcode }}'
        $pincode = '${{ github.event.inputs.pincode }}'
        Write-Host "Starting CRD with authcode: $authcode and pin: $pincode"

    # Timeout para manter a conexão ativa
    - name: Keep Alive
      shell: pwsh
      run: ./timeout.ps1

